//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HensMaarten_GPRd1._2_DM_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.TrainerTeams = new HashSet<TrainerTeam>();
        }
    
        public int id { get; set; }
        public string voornaam { get; set; }
        public string naam { get; set; }
        public string nationaliteit { get; set; }
        public System.DateTime geboorteDatum { get; set; }
        public Nullable<float> lengteInM { get; set; }
        public Nullable<int> gewichtInKG { get; set; }
        public Nullable<int> functieId { get; set; }
    
        public virtual Functie Functie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerTeam> TrainerTeams { get; set; }
    }
}
