//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HensMaarten_GPRd1._2_DM_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedstrijd
    {
        public int id { get; set; }
        public string uitslag { get; set; }
        public System.DateTime datum { get; set; }
        public int teamId { get; set; }
        public int tegenstanderId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Tegenstander { get; set; }
    }
}
